name: Build and Attach Release Packages

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-deb:
    name: Build DEB (${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Debian build deps
        run: |
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
            build-essential libpam0g-dev dpkg-dev debhelper devscripts fakeroot ca-certificates qemu-user-static binfmt-support

      - name: Build DEB (native or qemu)
        env:
          WERROR: "1"
        run: |
          make clean-packages || true
          make -j2 sudosh.1
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            make -j2 deb WERROR=1
          else
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker run --rm -v "$PWD":/src -w /src arm64v8/ubuntu:22.04 bash -lc '
              set -e;
              apt-get update -qq;
              DEBIAN_FRONTEND=noninteractive apt-get install -y -qq build-essential libpam0g-dev dpkg-dev debhelper devscripts fakeroot ca-certificates >/dev/null;
              make -j2 deb WERROR=1;
            '
          fi
          ls -al dist || true

      - name: Upload DEB to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-rpm:
    name: Build RPM (${{ matrix.distro }} ${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: el9
            image: almalinux:9
            arch: x86_64
          - distro: el9
            image: almalinux:9
            arch: aarch64
          - distro: el8
            image: rockylinux:8
            arch: x86_64
          - distro: el8
            image: rockylinux:8
            arch: aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build RPM in container
        run: |
          if [ "${{ matrix.arch }}" = "aarch64" ]; then
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            EMU_PREFIX="--platform linux/arm64/v8"
          else
            EMU_PREFIX=""
          fi
          docker run $EMU_PREFIX --rm -v "$PWD":/src -w /src ${{ matrix.image }} bash -lc '
            set -e;
            dnf -y -q install gcc make pam-devel rpm-build tar gzip which findutils git >/dev/null || \
              (yum -y -q install gcc make pam-devel rpm-build tar gzip which findutils git >/dev/null || true);
            git config --global --add safe.directory /src || true;
            make clean-packages >/dev/null || true;
            make -j2 rpm WERROR=1;
            ls -al dist;
          '

      - name: Upload RPMs to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.rpm
            dist/*.src.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

